from hist_data_analysis.analytics import analyse,similarity
from hist_data_analysis.sampling_rate import runme,undersampling_error
from hist_data_analysis.mTAN import hyper_tuning
from hist_data_analysis.mTAN import main as mTAN
from hist_data_analysis.interpolation import main as interpolation
from hist_data_analysis.interpolation import hyper_tuning as interp_hyper_tuning
from hist_data_analysis.correlate import correlate
from hist_data_analysis.visualize import main
from hist_data_analysis.classification_dataset import main as create_classif_data
from hist_data_analysis.train_ml_models import train_models