{
 "title": "NavGreen",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Calculated Thermal Flows",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"WATER_IN_COND\" or r._field == \"WATER_OUT_COND\" or r._field == \"FLOW_CONDENSER\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_CON_HEAT:\n           if r.FOUR_WAY_VALVE == \"True\" then 4.18*(998.0/3600.0*r.FLOW_CONDENSER)*(r.WATER_OUT_COND-r.WATER_IN_COND)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_CON_HEAT\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_CON_HEAT\")\n   |> keep(columns: [\"_time\", \"Q_CON_HEAT\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"WATER_IN_COND\" or r._field == \"WATER_OUT_COND\" or r._field == \"FLOW_CONDENSER\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_EVAP_COOL:\n           if r.FOUR_WAY_VALVE == \"False\" then 4.18*(998.0/3600.0*r.FLOW_CONDENSER)*(r.WATER_IN_COND-r.WATER_OUT_COND)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_EVAP_COOL\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_EVAP_COOL\")\n   |> keep(columns: [\"_time\", \"Q_EVAP_COOL\"])   "
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"WATER_IN_EVAP\" or r._field == \"WATER_OUT_EVAP\" or r._field == \"FLOW_EVAPORATOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"AIR_COOLED_COMMAND\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"AIR_COOLED_COMMAND\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_CON_COOL:\n           if r.AIR_COOLED_COMMAND == \"False\" and r.FOUR_WAY_VALVE == \"False\" then 4.18*(998.0/3600.0*r.FLOW_EVAPORATOR)*(r.WATER_OUT_EVAP-r.WATER_IN_EVAP)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_CON_COOL\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_CON_COOL\")\n   |> keep(columns: [\"_time\", \"Q_CON_COOL\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"WATER_IN_EVAP\" or r._field == \"WATER_OUT_EVAP\" or r._field == \"FLOW_EVAPORATOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"AIR_COOLED_COMMAND\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"AIR_COOLED_COMMAND\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_EVAP_HEAT:\n           if r.AIR_COOLED_COMMAND == \"False\" and r.FOUR_WAY_VALVE == \"True\" then 4.18*(998.0/3600.0*r.FLOW_EVAPORATOR)*(r.WATER_IN_EVAP-r.WATER_OUT_EVAP)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_EVAP_HEAT\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_EVAP_HEAT\")\n   |> keep(columns: [\"_time\", \"Q_EVAP_HEAT\"])  "
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"DHW_INLET\" or r._field == \"DHW_OUTLET\" or r._field == \"FLOW_DHW\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(fn: (r) => ({\n      r with Q_DHW: 4.18*(998.0/3600.0*r.FLOW_DHW)*(r.DHW_OUTLET-r.DHW_INLET)\n   }))\n   |> keep(columns: [\"_time\", \"Q_DHW\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_DHW\")\n   |> keep(columns: [\"_time\", \"Q_DHW\"])\n"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"SH1_IN\" or r._field == \"SH1_RETURN\" or r._field == \"FLOW_CONDENSER\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_HP_TANK_COOL:\n           if r.FOUR_WAY_VALVE == \"False\" then 4.18*(998.0/3600.0*r.FLOW_CONDENSER)*(r.SH1_RETURN-r.SH1_IN)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_HP_TANK_COOL\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_HP_TANK_COOL\")\n   |> keep(columns: [\"_time\", \"Q_HP_TANK_COOL\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"WATER_IN_COND\" or r._field == \"WATER_OUT_COND\" or r._field == \"FLOW_CONDENSER\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"THREE_WAY_COND_OPERATION\", \"Residential_office_mode\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"THREE_WAY_COND_OPERATION\", \"Residential_office_mode\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_HP_TANK_HEAT_OFF:\n           if r.THREE_WAY_COND_OPERATION == \"False\" and r.FOUR_WAY_VALVE == \"True\" and r.Residential_office_mode == \"True\" then 4.18*(998.0/3600.0*r.FLOW_CONDENSER)*(r.WATER_OUT_COND-r.WATER_IN_COND)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_HP_TANK_HEAT_OFF\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_HP_TANK_HEAT_OFF\")\n   |> keep(columns: [\"_time\", \"Q_HP_TANK_HEAT_OFF\"]) "
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"SH1_IN\" or r._field == \"SH1_RETURN\" or r._field == \"FLOW_CONDENSER\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"THREE_WAY_COND_OPERATION\", \"Residential_office_mode\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"THREE_WAY_COND_OPERATION\", \"Residential_office_mode\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n      fn: (r) => ({r with Q_HP_TANK_HEAT_RES:\n         if r.THREE_WAY_COND_OPERATION == \"True\" and r.FOUR_WAY_VALVE == \"True\" and r.Residential_office_mode == \"False\" then 4.18*(998.0/3600.0*r.FLOW_CONDENSER)*(r.SH1_IN-r.SH1_RETURN)\n         else 0.0 }),\n   )\n   |> keep(columns: [\"_time\", \"Q_HP_TANK_HEAT_RES\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_HP_TANK_HEAT_RES\")\n   |> keep(columns: [\"_time\", \"Q_HP_TANK_HEAT_RES\"])  "
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"PVT_OUT\" or r._field == \"PVT_IN\" or r._field == \"FLOW_PVT\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(fn: (r) => ({\n      r with Q_PVT: (3.6014+0.004*(r.PVT_IN + r.PVT_OUT)/2.0 - 0.000002*((r.PVT_IN + r.PVT_OUT)/2.0)^2.0)*((1049.0-0.475*(r.PVT_IN + r.PVT_OUT)/2.0-0.0018*((r.PVT_IN + r.PVT_OUT)/2.0)^2.0)/1000.0/3600.0*r.FLOW_PVT)*(r.PVT_OUT + r.PVT_IN)\n   }))\n   |> keep(columns: [\"_time\", \"Q_PVT\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_PVT\")\n   |> keep(columns: [\"_time\", \"Q_PVT\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"PVT_IN_TO_SOLAR_BUFFER\" or r._field == \"PVT_OUT_FROM_SOLAR_BUFFER\" or r._field == \"FLOW_PVT\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"THREE_WAY_SOLAR_OPERATION\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"THREE_WAY_SOLAR_OPERATION\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_PVT_SOLAR_BUFFER:\n           if r.THREE_WAY_SOLAR_OPERATION == \"False\" then (3.6014+0.004*(r.PVT_IN_TO_SOLAR_BUFFER+r.PVT_OUT_FROM_SOLAR_BUFFER)/2.0 - 0.000002*((r.PVT_IN_TO_SOLAR_BUFFER+r.PVT_OUT_FROM_SOLAR_BUFFER)/2.0)^2.0)*((1049.0- 0.475*(r.PVT_IN_TO_SOLAR_BUFFER+r.PVT_OUT_FROM_SOLAR_BUFFER)/2.0-0.0018*((r.PVT_IN_TO_SOLAR_BUFFER+r.PVT_OUT_FROM_SOLAR_BUFFER)/2.0)^2.0)/1000.0/3600.0*r.FLOW_PVT)*(r.PVT_IN_TO_SOLAR_BUFFER+r.PVT_OUT_FROM_SOLAR_BUFFER)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_PVT_SOLAR_BUFFER\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_PVT_SOLAR_BUFFER\" )\n   |> keep(columns: [\"_time\", \"Q_PVT_SOLAR_BUFFER\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"PVT_IN_TO_DHW\" or r._field == \"PVT_OUT_FROM_DHW\" or r._field == \"FLOW_PVT\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"THREE_WAY_SOLAR_OPERATION\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"THREE_WAY_SOLAR_OPERATION\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_PVT_DHW:\n           if r.THREE_WAY_SOLAR_OPERATION == \"True\" then (3.6014+0.004*(r.PVT_IN_TO_DHW + r.PVT_OUT_FROM_DHW)/2.0 - 0.000002*((r.PVT_IN_TO_DHW + r.PVT_OUT_FROM_DHW)/2.0)^2.0)*((1049.0- 0.475*(r.PVT_IN_TO_DHW + r.PVT_OUT_FROM_DHW)/2.0 -0.0018*((r.PVT_IN_TO_DHW + r.PVT_OUT_FROM_DHW)/2.0)^2.0)/1000.0/3600.0*r.FLOW_PVT)*(r.PVT_IN_TO_DHW - r.PVT_OUT_FROM_DHW)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_PVT_DHW\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_PVT_DHW\")\n   |> keep(columns: [\"_time\", \"Q_PVT_DHW\"])\n"
    },
    {
     "query": "   from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"WATER_IN_COND\" or r._field == \"WATER_OUT_COND\" or r._field == \"FLOW_CONDENSER\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"THREE_WAY_COND_OPERATION\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"THREE_WAY_COND_OPERATION\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_HP_DHWtank:\n           if r.THREE_WAY_COND_OPERATION == \"False\" and r.FOUR_WAY_VALVE == \"True\" then (4.18*(998.0/3600.0*r.FLOW_CONDENSER)*(r.WATER_OUT_COND-r.WATER_IN_COND))\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_HP_DHWtank\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_HP_DHWtank\" )\n   |> keep(columns: [\"_time\", \"Q_HP_DHWtank\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"BTES_TANK_IN\" or r._field == \"BTES_TANK_OUT\" or r._field == \"FLOW_EVAPORATOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"THREE_WAY_EVAP_OPERATION\", \"AIR_COOLED_COMMAND\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"THREE_WAY_EVAP_OPERATION\", \"AIR_COOLED_COMMAND\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_BTES_HP_COOL:\n           if r.THREE_WAY_EVAP_OPERATION == \"False\" and r.FOUR_WAY_VALVE == \"False\" and r.AIR_COOLED_COMMAND == \"False\" then 4.18*(998.0/3600.0*r.FLOW_EVAPORATOR)*(r.BTES_TANK_IN-r.BTES_TANK_OUT)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_BTES_HP_COOL\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_BTES_HP_COOL\")\n   |> keep(columns: [\"_time\", \"Q_BTES_HP_COOL\"]) "
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"BTES_TANK_IN\" or r._field == \"BTES_TANK_OUT\" or r._field == \"FLOW_EVAPORATOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"THREE_WAY_EVAP_OPERATION\", \"AIR_COOLED_COMMAND\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"THREE_WAY_EVAP_OPERATION\", \"AIR_COOLED_COMMAND\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_BTES_HP_HEAT:\n           if r.THREE_WAY_EVAP_OPERATION == \"False\" and r.FOUR_WAY_VALVE == \"True\" and r.AIR_COOLED_COMMAND == \"False\" then 4.18*(998.0/3600.0*r.FLOW_EVAPORATOR)*(r.BTES_TANK_OUT-r.BTES_TANK_IN)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_BTES_HP_HEAT\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_BTES_HP_HEAT\")\n   |> keep(columns: [\"_time\", \"Q_BTES_HP_HEAT\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"SOLAR_BUFFER_IN\" or r._field == \"SOLAR_BUFFER_OUT\" or r._field == \"FLOW_EVAPORATOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\", \"FOUR_WAY_VALVE\", \"THREE_WAY_EVAP_OPERATION\", \"AIR_COOLED_COMMAND\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\", \"FOUR_WAY_VALVE\", \"THREE_WAY_EVAP_OPERATION\", \"AIR_COOLED_COMMAND\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(\n       fn: (r) => ({r with Q_SOLAR_BUFFER_HP:\n           if r.THREE_WAY_EVAP_OPERATION == \"False\" and r.FOUR_WAY_VALVE == \"True\" and r.AIR_COOLED_COMMAND == \"False\" then 4.18*(998.0/3600.0*r.FLOW_EVAPORATOR)*(r.SOLAR_BUFFER_OUT-r.SOLAR_BUFFER_IN)\n           else 0.0 }),\n    )\n   |> keep(columns: [\"_time\", \"Q_SOLAR_BUFFER_HP\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_SOLAR_BUFFER_HP\")\n   |> keep(columns: [\"_time\", \"Q_SOLAR_BUFFER_HP\"]) "
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"SH_INLET\" or r._field == \"SH_RETURN\" or r._field == \"FLOW_FAN_COILS_INDOOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(fn: (r) => ({\n      r with Q_TANK_BUILD_HEAT: 4.18*(998.0/3600.0*r.FLOW_FAN_COILS_INDOOR)*(r.SH_INLET-r.SH_RETURN)\n   }))\n   |> keep(columns: [\"_time\", \"Q_TANK_BUILD_HEAT\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_TANK_BUILD_HEAT\")\n   |> keep(columns: [\"_time\", \"Q_TANK_BUILD_HEAT\"])"
    },
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n   |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n   |> filter(fn: (r) => r._measurement == \"temperature\" or r._measurement == \"flow\")\n   |> filter(fn: (r) => r._field == \"SH_INLET\" or r._field == \"SH_RETURN\" or r._field == \"FLOW_FAN_COILS_INDOOR\")\n   |> keep(columns: [\"_time\", \"_field\", \"_value\"])\n   |> group(columns: [\"_time\"], mode: \"by\")\n   |> pivot(rowKey: [\"_time\"], columnKey: [\"_field\"], valueColumn: \"_value\")\n   |> map(fn: (r) => ({\n      r with Q_TANK_BUILD_COOL: 4.18*(998.0/3600.0*r.FLOW_FAN_COILS_INDOOR)*(r.SH_RETURN-r.SH_INLET)\n   }))\n   |> keep(columns: [\"_time\", \"Q_TANK_BUILD_COOL\"])\n   |> group()\n   |> aggregateWindow(every: v.windowPeriod, fn: max, column: \"Q_TANK_BUILD_COOL\")\n   |> keep(columns: [\"_time\", \"Q_TANK_BUILD_COOL\"])"
    }
   ]
  },
  {
   "title": "Control",
   "type": "state-timeline",
   "gridPos": { "h": 8, "w": 17, "x": 3, "y": 10 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"control\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: last)\n"
    }
   ]
  },
  {
   "title": "Power",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"power\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  { "title": "Row title", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 } },
  {
   "title": "Other : EEV_LOAD1, EEV_LOAD2",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"other\")\n    |> filter(fn: (r) => r._field == \"EEV_LOAD1\" or r._field ==  \"EEV_LOAD2\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Other : Compressor HZ",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 29 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"other\" and r._field == \"Compressor_HZ\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Solar",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 39 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"solar\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Flow",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 49 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"flow\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Pressures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 60 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"pressure\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)"
    }
   ]
  },
  {
   "title": "Temperatures",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 71 },
   "targets": [
    {
     "query": "from(bucket: \"mult_source_heatpump\")\n    |> range(start: v.timeRangeStart, stop: v.timeRangeStop)\n    |> filter(fn: (r) => r._measurement == \"temperature\")\n    |> keep( columns: [ \"id\", \"_field\", \"_value\", \"_time\"] )\n    |> aggregateWindow(every: v.windowPeriod, fn: mean)\n \n"
    }
   ]
  }
 ]
}