seeds: [6, 72] # [6, 72, 157, 838, 1214, 1505]
bins: ["FixedBin" , "ValueCountBin", "ValueRangeBin"]

time_reprs:
  1:
    dts: ["date"]
    cors: ["triangular_pulse"]
    uniqs: ["linear"]
    args:
      - [[None, None, None], [None, None, None]]
  2:
    dts: ["month", "hour"]
    cors: ["sine", "cosine"]
    uniqs: ["sine", "cosine"]
    args:
      - [[12, None, 0], [12, None, 0]]
      - [[24, None, 0], [24, None, 0]]
  3:
    dts: ["month", "hour"]
    cors: ["sine", "cosine"]
    uniqs: ["sawtooth", "sawtooth"]
    args:
      - [[6, None, 1.5708], [6, None, 6]]
      - [[12, None, 1.5708], [12, None, 12]]